<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <h1>
        Barbecue
    </h1>
    <p>
        On the 31st of August 2018, the introduction committee will organise the introduction day for new Artificial Intelligence and Computing Science first year students. There will be a concluding barbecue, and if you're a first year student, this will be free of charge!
    </p>
    <p>
        The sign up form is coming soon!
    </p>
</div>
<?php $this->end() ?>
