<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<img src="/static/img/logo-banner.png" class="banner">
<div class="container container-narrow">
    <section>
        <h1>
            Introduction
        </h1>
        <p>
            Welcome to the wonderful website of the Introduction Committee of 2018 of Cover. We, the Introduction Committee, are really proud to have organised this year's camp for you from the 7<sup>th</sup> till the 9<sup>th</sup> of September. We thought it was a wonderful experience and would like to thank all participants, as well as the HEROcee for providing first aid, and all other senior students to help us make the camp go as smoothly as it did.
        </p>
        <p>
            On the Saturday evening, we played a role playing game. A game during which all the first-year students had to gather money by running errands for dressed up senior students. Of course, as is tradition, we created a lovely movie to introduce the games and even a concluding movie, which was shown after the game had ended. In case you wish to experience a blast to the past and view the videos once more, they're listed below. Enjoy!
        </p>
    </section>
    <section>
        <h2>
            Introduction movie
        </h2>
        <video controls height="auto" width="100%" preload="metadata">
            <source src="/static/video/video.mp4" type="video/mp4">
            <source src="/static/video/video.mov" type="video/mov">
                Your browser does not support this type of media.
        </video>
    </section>
    <section>
        <h2>
            Concluding movie
        </h2>
        <video controls height="auto" width="100%" preload="metadata">
            <source src="/static/video/video.mp4" type="video/mp4">
            <source src="/static/video/video.mov" type="video/mov">
                Your browser does not support this type of media.
        </video>
    </section>
</div>
<?php $this->end() ?>
