<?php $this->extends('layout.phtml') ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/committee.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="container container-wide">
    <div id=committee-member style="height: auto">
        <h1>Meet the crew!</h1>
        <div>
            <img src="/static/img/committee.jpg" class="committee-photo">
        </div>
    </div>
    <hr>
    <div id=committee-member>
        <div id=committee-photo-left>
            <img src="/static/img/jip.jpeg" class="committee-member-photo">
        </div>
        <div id=committee-text-right>
            <h1>Jip Maijers</h1>
            <h2>Chairman</h2>
            <p>
                Jip Maijers, what a handsome guy. With his blonde manes and those dreamy eyes.. wowow REWIND! Okay, Jip has been a member of uncountable committees of Cover, which makes him the undisputed chairman. He can be serious when he needs to be (which sometimes is necessary with this bunch), but to be honest nothing makes him happier than some nerdy jokes. He might act cool and tough, but don't let this fool you! Jip is one sweet cookie on the inside, and will help where and whenever he can. So, if you have a struggle, need manly guidance or just a new friend? Have funny dog videos, love Pokémon, gaming and chicken nuggets? Jip's your guy!  
            </p>
        </div>
    </div>
    <hr>
    <div id=committee-member>
        <div id=committee-photo-right>
            <img src="/static/img/marleen.jpeg" class="committee-member-photo">
        </div>
        <div id=committee-text-left>
            <h1>Marleen Schumacher</h1>
            <h2>Vice-Chairman</h2>
            <p>
                Marleen Schumacher, no she ain't a speed devil (yet), like the other Schumacher you may know. But, the thing she is quick with, is her witty remarks and finishing her to-do list. But even then, she can be quite patient with the people around her, which is certainly a good property to have, seeing as she has to deal with the people in this committee. She is so helpful that she even gives feedback on someone else's writing even when nobody asked her. If you need someone reliable and fun, Marleen is the one you should be looking for.
            </p> 
        </div>
    </div>
    <hr>
    <div id=committee-member>
        <div id=committee-photo-left>
            <img src="/static/img/chris.jpeg" class="committee-member-photo">
        </div>
        <div id=committee-text-right>
            <h1>Chris Ausema</h1>
            <h2>Secretary</h2>
            <p>
                This piece has not been written yet.
            </p>
        </div>
    </div>
    <hr>
    <div id=committee-member>
        <div id=committee-photo-right>
            <img src="/static/img/yannick.jpeg" class="committee-member-photo">
        </div>
        <div id=committee-text-left>
            <h1>Yannick Stoffers</h1>
            <h2>Treasurer</h2>
            <p>
                Anyone who is a member of Cover for longer than a week but has not yet met Yannick, must be doing something wrong. In Yannick’s opinion, being a board member and a member of the IntroCee is not even close to being active enough at Cover. Therefore, he is a member of three (!!) more committees. Especially his position in the YearbookCee is worth mentioning, so do not hesitate to ask him what this is. Besides the fact that it is quite difficult not to meet Yannick when joining Cover, it is also a shame since he is not only one of the nicest persons you will meet around here, but without a doubt also the best solver of Rubik’s Cubes. 
            </p>
        </div>
    </div>
    <hr>
    <div id=committee-member>
        <div id=committee-photo-left>
            <img src="/static/img/feline.jpeg" class="committee-member-photo">
        </div>
        <div id=committee-text-right>
            <h1>Feline van Aagten</h1>
            <h2>Senior Advisor</h2>
            <p>
                Feline, or Fe, is our senior advisor. Why, you ask? Because this is not the first time she is a member of the IntroCee. It's also not the second time. Fe is a member of this silly bunch for the third time! In fact, she has been the chairwoman of the IntroCee as well. That makes her the perfect person to tell the rest of the committee that we are too soft for the first year students, or of course, when it's time to consume a leermoment, as it's called. If you don't know what that is, then don't worry, meet Fe, tell her she's not a very nice person and she'll gladly make you consume a leermoment. Feline may not be the oldest member of the IntroCee, but she is definitely the wisest, so when you need advice on anything, don't hesitate to ask her!
            </p>
        </div>
    </div>
    <hr>
    <div id=committee-member>
        <div id=committee-photo-right>
            <img src="/static/img/gerritjan.png" class="committee-member-photo">
        </div>
        <div id=committee-text-left>
            <h1>Gerrit-jan van der Sloot</h1>
            <h2>Ketel kanjer</h2>
            <p>
                This piece has not been written yet.
            </p>
        </div>
    </div>
    <hr>
    <div id=committee-member>
        <div id=committee-photo-left>
            <img src="/static/img/benjamin.jpeg" class="committee-member-photo">
        </div>
        <div id=committee-text-right>
            <h1>Benjamin Dinh</h1>
            <h2>General Member</h2>
            <p>
                Also known as Bennieboi, which is his preferred nickname. Bennieboi is currently entering his second year as an AI student. He is very creative with art, and always brings a joyful atmosphere to our committee, for which we appreciate him. His favourite animal is a cat, and if he were to be a plant, he would have been a weeping willow. This is very interesting considering the fact that if he were to be a sandwich, he would have been a salmon bagel. What kind of meaning this has is up to you. His other skills include serving beer, funny voices, and he can do a very special trick with his eyes, which is simply amazing.
            </p>
        </div>
    </div>
    <hr>
    <div id=committee-member>
        <div id=committee-photo-right>
            <img src="/static/img/coenraad.png" class="committee-member-photo">
        </div>
        <div id=committee-text-left>
            <h1>Coenraad Holstege</h1>
            <h2>General Member</h2>
            <p>
                Coenraad, or Coen as we like to call him, is a second year AI student. When you first look at him, you might be led to believe that is he is just another guy who likes to go to the gym, play the occasional video game or cracking open a cold one with the boys. What you would not immediately think is that Coen plays the guitar really well! At the end of a not so eventful evening, Coen mesmerized us with his guitar skills and promised to play for us all at the campfire. So if you like to sing, you better start picking some songs, because Coen will happily accompany you! Morning deadlines are a fright of all students, but this doesn’t bother Coen. He carelessly goes out the night before, knowing he’ll meet the deadline. But how? This is Cover's best kept secret, an ability most students would love to have. Get to know Coen and maybe, just maybe, you’ll unravel the secret!
            </p>
        </div>
    </div>
</div>
<?php $this->end() ?>
