<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="container container-wide">
    <h1>Grab list</h1>
    <div class="jumbotron">
        <h2>Make sure you've got everything covered!</h2>
        <div class="row navPadding" id="paklijst">
            <div class="col-lg-6">
                <h3>Sleeping</h3>
                <ul class="list-group">
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="pillow" onclick="setCookie('pillow')">
                        Pillow
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="sleeping-bag" onclick="setCookie('sleeping-bag')">
                        Sleeping bag or blanket cover 
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="pyjamas" onclick="setCookie('pyjamas')">
                        Pyjamas
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="pillowcase" onclick="setCookie('pillowcase')">
                        Pillowcase
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="sheets" onclick="setCookie('sheets')">
                        Sheets
                    </li>
                </ul>
            </div>
            <div class="col-lg-6">
                <h3>Personal Care</h3>
                <ul class="list-group">
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="towel" onclick="setCookie('towel')">
                        Towel
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="toothbrush" onclick="setCookie('toothbrush')">
                        Toothbrush
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="toothpaste" onclick="setCookie('toothpaste')">
                        Toothpaste
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="shampoo" onclick="setCookie('shampoo')">
                        Soap/Shampoo
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="washcloth" onclick="setCookie('washcloth')">
                        Washcloth
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="deodorant" onclick="setCookie('deodorant')">
                        Deodorant
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="sun-block" onclick="setCookie('sun-block')">
                        Sun block
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="medicine" onclick="setCookie('medicine')">
                        Medicine (if applicable)
                    </li>
                </ul>
            </div>
            <div class="col-lg-6">
                <h3>Clothing</h3>
                <ul class="list-group">
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="dirty" onclick="setCookie('dirty')">
                        Clothes for getting dirty
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="pants" onclick="setCookie('pants')">
                        Long pants
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="shorts" onclick="setCookie('shorts')">
                        Shorts
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="shoes" onclick="setCookie('shoes')">
                        Old shoes
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="socks" onclick="setCookie('socks')">
                        Socks
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="underwear" onclick="setCookie('underwear')">
                        Underwear
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="shirts" onclick="setCookie('shirts')">
                        Shirts
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="swimwear" onclick="setCookie('swimwear')">
                        Swimwear
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="hoodie" onclick="setCookie('hoodie')">
                        Warm jacket/hoodie
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="garbage" onclick="setCookie('garbage')">
                        (Garbage) bag for dirty clothes
                    </li>
                </ul>
            </div>
            <div class="col-lg-6">
                <h3>Others</h3>
                <ul class="list-group">
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="identification" onclick="setCookie('identification')">
                        Identification
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="cutlery" onclick="setCookie('cutlery')">
                        Cutlery
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="plate" onclick="setCookie('plate')">
                        Plate
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="dishcloth" onclick="setCookie('dishcloth')">
                        Dishcloth
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="phone" onclick="setCookie('phone')">
                        Phone and charger (optional)
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="cup" onclick="setCookie('cup')">
                        Drinking cup
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="water-gun" onclick="setCookie('water-gun')">
                        Water gun
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="time-killer" onclick="setCookie('time-killer')">
                        Something to do during breaks, like a book or games (optional)
                    </li>
                    <li class="list-group-item">
                        <input type="checkbox" value="" id="cigarettes" onclick="setCookie('cigarettes')">
                        For smokers: cigarettes (optional, there is no option to buy them during the camp)
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php $this->end() ?>

<?php $this->begin('scripts') ?>
<script type="text/javascript">
    function setCookie(name){
        var c = name + "=" + document.getElementById(name).checked + ";"

        var d = new Date();
        d.setTime(d.getTime() + (30*24*60*60*1000));
        var expires = "expires="+ d.toUTCString();

        document.cookie = c + expires;
        console.log (c + expires);
    }

    window.onload = function getCookie(){
        var ca = document.cookie.split(";");
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            var elem = c.split("=");
            console.log(elem);
            if (elem[0] != "expires") {
                document.getElementById(elem[0]).checked = (elem[1] == "true");
            }
        }
        console.log (ca)
    }
</script>
<?php $this->end() ?>
