<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<img src="/static/img/logo-banner.png" class="banner">
<div class="container container-narrow">
    <section>
        <h1>
            Introduction
        </h1>
        <p>
            Welcome to the wonderful website of the Introduction Committee of 2018 of Cover. Are you starting the Bachelor Artificial Intelligence or Computing Science at the University of Groningen in 2018? Join the introduction camp organised by study association Cover! This is the opportunity to get to know your fellow students in a fun way and to make some new friends. We, the Introduction Committee, are really proud to organise this year's camp for you from the 7th till the 9th of September. 
        </p>
        <p>
            Throughout the entire weekend there will be a fun programme full of nice activities to meet a lot of new people (both first years and a bunch of senior students). What's more is that there is plenty of time to do just about anything else and have fun with your new friends or play some cards. In other words, spending the first weekend as a student at this camp is the best way to get a head start in your new life as a student!
        </p>
    </section>
    <section>
        <h1>
            Theme
        </h1>
        <p>
            The theme this year is "Rewind: A Blast to the Past". Make sure to dig up your inner child, and relive all those wonderful moments you experienced years ago, but with a new twist. Instead of watching your favourite series or playing your favourite games from your youth, watch them come alive and interact with each other.
        </p>
        <p>
            Do you remember all 150 original Pokémon, Fairly Odd Parents, or are you old enough to have played Tetris and Pacman, or did you see the original trilogy of Star Wars in the cinema? Probably not the latter, but hey, we couldn't leave those movies out, could we? Sign up now, and experience a weekend to remember for the remainder of your study time in Groningen, and probably far beyond then. In 30 years, memories of this introduction camp will be a Blast to the Past for your future self!
        </p>
        <p>
            For an impression, see the aftermovie of last year's camp:
        </p>
        <div class="video">
            <iframe class="iframe-video" src="https://www.youtube-nocookie.com/embed/Ri7FL9maKXc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
    </section>
    <section>
        <h1>Contact</h1>
        <div class="jumbotron">
            <h3>
                <img src="/static/icons/mail.png" class="icon">
                <small>introcee@svcover.nl</small>
                <br>
            
                <img src="/static/icons/phone.png" class="icon">
                <small>Jip Maijers (Chairman of the IntroCee): +31 6 50 61 18 15</small>
            </h3>
        </div>
    </section>
    <section>
        <h1>
            Location
        </h1>
        <p>
            This introductory camp will take place at a well-suited accommodation called <a href="http://www.pagedal.nl/Conferentielocatie/Faciliteiten/Groepsaccommodatie">Pagedal</a> in the tiny town near Groningen called Stadskanaal, which itself is situated at the border between Groningen and Drenthe. Our departure from the university will be on Friday afternoon at 15:00, at which time a bus will take us straight to the campsite. As we made sure that you are completely free that Friday afternoon, you won't have to worry about missing any classes. Sometime on Sunday afternoon, after all the fun is said and done, we will travel back to Groningen Central Station or Zernike Campus and we hope you will take some amazing memories with you.
        </p>
    </section>
</div>
<div class="iframe-rwd">
    <iframe width="100%" height="750px" max-height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2401.4175536205385!2d6.97653941582522!3d52.99487607990686!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47b7c5497949e8b5%3A0xb0e273677d48e28b!2sPagedal+Conferentiecentrum!5e0!3m2!1snl!2snl!4v1490020148711"></iframe>
</div>
<?php $this->end() ?>
