<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php if (!empty($title)):?><?= $title ?> &mdash; <?php endif ?> Cover introduction camp 2018</title>
    
    <!-- Include stylesheets -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type='text/css'>
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type='text/css'>
    <link rel="stylesheet" href="//cdl.svcover.nl/css/cdl.css" type="text/css">
    <link rel="stylesheet" href="/static/css/introcee.css" type="text/css">
    <?= !empty($styles) ? $styles : ''?>
</head>
<body>
    <nav class="navbar navbar-cover">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed navicon-button" href="#navbar-main-collapse" data-toggle="collapse" aria-expanded="false" aria-controls="navbar-main-collapse">
                    <span class="navicon navicon-white"></span>
                </button>
                <a href="//www.svcover.nl/" class="navbar-logo"><img src="//sd.svcover.nl/Logos/Cover/white/cover_logo_white.svg" alt="Cover"></a>
                <a href="#" class="navbar-brand">Introduction camp 2018</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-main-collapse">
                <ul class="navbar-right">
                    <li <?php if ($page_id == 'index'): ?>class="active"<?php endif ?> >
                        <a href="index.php">Home</a>
                    </li>
                    <li <?php if ($page_id == 'committee'): ?>class="active"<?php endif ?> >
                        <a href="committee.php">Organisation</a>
                    </li>
                    <li <?php if ($page_id == 'grablist'): ?>class="active"<?php endif ?> >
                        <a href="grablist.php">Grab list</a>
                    </li>
                    <li <?php if ($page_id == 'signup'): ?>class="active"<?php endif ?> >
                        <a href="signup.php">Sign up</a>
                    </li>
                    <li <?php if ($page_id == 'barbecue'): ?>class="active"<?php endif ?> >
                        <a href="barbecue.php">Barbecue</a>
                    </li>
                    <?php if(cover_session_logged_in() && cover_session_in_committee(ADMIN_COMMITTEE)): ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header">Admin</li>
                                <li><a href="signup_admin.php">Registrations</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="dropdown-header">Logged in as <?= $this->html(get_cover_session()->voornaam) ?></li>
                                <li><a href="<?= cover_logout_url() ?>">Logout</a></li>
                            </ul>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Insert rendered content -->
    <?= $content ?>

    <!-- Ìnclude scripts -->
    <script src="/static/js/jquery-1.11.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <?= !empty($scripts) ? $scripts : '' ?>
</body>
</html>
