<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <h1>Sign up</h1>
    <h2>Introduction camp</h2>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        The camp has already passed. It was from the 7<sup>th</sup> till the 9<sup>th</sup> of September 2018.
    </div>
</div>
<?php $this->end() ?>
