<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <h1>Sign up</h1>
    <h2>Barbecue on the introduction day</h2>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        We're sorry, but the online sign-ups have closed. In case you still wish to participate in the barbecue on the introduction day on the 31<sup>st</sup> of September 2018, please approach the bar outside the Bernoulliborg.
    </div>

    <h2>Location of the bar:</h2>
</div>
<iframe width="100%" height="750px" max-height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d596.9401672632199!2d6.5358649292978335!3d53.24006639874732!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c9cd1a480c9101%3A0xaac9d66e86f00a18!2sUnnamed+Road%2C+9747+AG+Groningen!5e0!3m2!1sen!2snl!4v1535641070563"></iframe>
<?php $this->end() ?>
