<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <h1>Sign up</h1>
    <div class="jumbotron">
        <div class="tab">
            <button class="tablinks" onclick="openForm(event, 'foet')" id="defaultOpen"><h3>First-year students</h3></button>
            <button class="tablinks" onclick="openForm(event, 'senior')"><h3>Senior students</h3></button>
        </div>
        <div class="tabcontent" id="foet">
            <form>
                <h3>Personal</h3>
                <div class="form-group">
                    <label for="s-number">Student number</label>
                    <input id="s-number" type="text" name="s-number" class="form-control" placeholder="s1234567">
                </div>
                <div class="form-group">
                    <label for="first-name">First Name</label>
                    <input id="first-name" type="text" name="first-name" class="form-control" placeholder="Jan">
                </div>
                <div class="form-group">
                    <label for="family-name">Surname</label>
                    <input id="family-name" type="text" name="surname" class="form-control" placeholder="de Joker">
                </div>
                <div class="form-group">
                    <label for="Date-of-birth">Date of birth</label>
                    <input id="Date-of-birth" type="date" name="Date-of-birth" class="form-control" placeholder="20-09-1993">
                </div>

                <h3>Contact</h3>
                <div class="form-group">
                    <label for="address">Street name + number</label>
                    <input id="address" type="text" name="address" class="form-control" placeholder="Nijenborgh 9">
                </div>
                <div class="form-group">
                    <label for="zipcode">Zipcode</label>
                    <input id="zipcode" type="text" name="zipcode" class="form-control" placeholder="9747 AG">
                </div>
                <div class="form-group">
                    <label for="city">City</label>
                    <input id="city" type="text" name="city" class="form-control" placeholder="Groningen">
                </div>
                <div class="form-group">
                    <label for="phone-number">Phone number</label>
                    <input id="phone-number" type="text" name="phone-number" class="form-control" placeholder="+3150 363 6898">
                </div>
                <div class="form-group">
                    <label for="mail">E-mail</label>
                    <input id="mail" type="text" name="mail" class="form-control" placeholder="introcee@svcover.nl">
                </div>
                <div class="form-group">
                    <label for="emergency-contact">Emergency contact</label>
                    <input id="emergency-contact" type="text" name="emergency-contact" class="form-control" placeholder="+3150 363 6898">
                </div>

                <h3>Financial</h3>
                <div class="form-group">
                    <label for="iban">IBAN</label>
                    <input id="iban" type="text" name="iban" class="form-control" placeholder="NL37BANK0123456789">
                </div>
                <div class="form-group">
                    <label for="bic">BIC (only for non-Dutch bank accounts)</label>
                    <input id="bic" type="text" name="bic" class="form-control" placeholder="BANKNL2G">
                </div>

                <h3>Other</h3>
                <div class="form-group">
                    <label for="field-of-study">Field of study</label>
                    <select class="form-control" id="field-of-study">
                        <option value="ai">Artificial Intelligence</option>
                        <option value="cs">Computing Science</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="comment">Comments</label>
                    <textarea id="comment" class="form-control" rows="3" placeholder="Comments (allergies, medication, remarks)"></textarea>    
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="vega" value="">
                        I'm a vegetarian
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="terms" value="">
                        I have read and accepted the terms and conditions
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="costs" value="">
                        I have accepted the costs of &euro; 45,-
                    </label>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>

        <div class="tabcontent" id="senior">
            <form>
                <h3>Personal</h3>
                <div class="form-group">
                    <label for="first-name">First Name</label>
                    <input id="first-name" type="text" name="first-name" class="form-control" placeholder="Jan">
                </div>
                <div class="form-group">
                    <label for="family-name">Surname</label>
                    <input id="family-name" type="text" name="surname" class="form-control" placeholder="de Joker">
                </div>
                <div class="form-group">
                    <label for="Date-of-birth">Date of birth</label>
                    <input id="Date-of-birth" type="date" name="Date-of-birth" class="form-control" placeholder="20-09-1993">
                </div>

                <h3>Contact</h3>
                <div class="form-group">
                    <label for="address">Street name + number</label>
                    <input id="address" type="text" name="address" class="form-control" placeholder="Nijenborgh 9">
                </div>
                <div class="form-group">
                    <label for="zipcode">Zipcode</label>
                    <input id="zipcode" type="text" name="zipcode" class="form-control" placeholder="9747 AG">
                </div>
                <div class="form-group">
                    <label for="city">City</label>
                    <input id="city" type="text" name="city" class="form-control" placeholder="Groningen">
                </div>
                <div class="form-group">
                    <label for="phone-number">Phone number</label>
                    <input id="phone-number" type="text" name="phone-number" class="form-control" placeholder="+3150 363 6898">
                </div>
                <div class="form-group">
                    <label for="mail">E-mail</label>
                    <input id="mail" type="text" name="mail" class="form-control" placeholder="introcee@svcover.nl">
                </div>
                <div class="form-group">
                    <label for="emergency-contact">Emergency contact</label>
                    <input id="emergency-contact" type="text" name="emergency-contact" class="form-control" placeholder="+3150 363 6898">
                </div>

                <h3>Financial</h3>
                <div class="form-group">
                    <label for="iban">IBAN</label>
                    <input id="iban" type="text" name="iban" class="form-control" placeholder="NL37BANK0123456789">
                </div>
                <div class="form-group">
                    <label for="bic">BIC (only for non-Dutch bank accounts)</label>
                    <input id="bic" type="text" name="bic" class="form-control" placeholder="BANKNL2G">
                </div>

                <h3>Other</h3>
                <div class="form-group">
                    <label for="field-of-study">Field of study</label>
                    <select class="form-control" id="field-of-study">
                        <option value="ai">Artificial Intelligence</option>
                        <option value="cs">Computing Science</option>
                        <option value="other">Other</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="year-of-study">I have been studying for</label>
                    <select class="form-control" id="year-of-study">
                        <option value="1">1 year</option>
                        <option value="2">2 years</option>
                        <option value="3">3 years</option>
                        <option value="4">4 years</option>
                        <option value="5">5 years</option>
                        <option value="6">6 years</option>
                        <option value="7">7 years</option>
                        <option value="8">8 years</option>
                        <option value="9">9 years</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="comment">Comments</label>
                    <textarea id="comment" class="form-control" rows="3" placeholder="Comments (allergies, medication, remarks)"></textarea>    
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="mentor" value="">
                        I'm a mentor
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="vega" value="">
                        I'm a vegetarian
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="terms" value="">
                        I have read and accepted the terms and conditions
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="costs" value="">
                        I have accepted the costs of &euro; 55,-
                    </label>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
</div>
<?php $this->end() ?>

<?php $this->begin('scripts') ?>
<script type="text/javascript">
    function openForm(evt, formName) {
        // Declare all variables
        var i, tabcontent, tablinks;

        // Get all elements with class="tabcontent" and hide them
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        // Get all elements with class="tablinks" and remove the class "active"
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }

        // Show the current tab, and add an "active" class to the button that opened the tab
        document.getElementById(formName).style.display = "block";
        evt.currentTarget.className += " active";
    }

    // Open the default tab.
    document.getElementById("defaultOpen").click();
</script>
<?php $this->end() ?>

