<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <h1>Sign up</h1>
    <h2>Introduction camp</h2>
    <?php if (cover_session_logged_in()): ?>
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Hi <?= get_cover_session()->voornaam ?>! We prefilled the form with some your information from the Cover website.
        </div>
    <?php else: ?>
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Hi there! Did you know, that if you log in on the Cover website (membership required) we can pretty much fill in most of this information already? You can log in <a href='//www.svcover.nl/sessions.php'>here</a>, or sign up <a href='//www.svcover.nl/lidworden.php'>here</a>.
        </div>
    <?php endif ?>

    <ul class="nav nav-pills nav-justified" role="tablist">
        <li role="presentation" <?php if ($form->get_value('type') == 'First-year'): ?>class="active"<?php endif ?>>
            <a href="#first-year" aria-controls="first-year" role="tab" data-toggle="tab">First-year students</a>
        </li>
        <li role="presentation" <?php if ($form->get_value('type') != 'First-year'): ?>class="active"<?php endif ?>>
            <a href="#senior" aria-controls="senior" role="tab" data-toggle="tab">Senior students</a>
        </li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane <?=($form->get_value('type') == 'First-year') ? 'active' : '' ?>" id="first-year">
            <?php if (count( array_filter(get_model('Registration')->get(), function ($p) {
                    return $p['status'] === 'registered' && $p['type'] === 'First-year';
                })) >= 120): ?>
                <p>
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    At this moment all the reserved spots for the introductory camp are taken. You can still sign up, and we recommend to do so, but you will be placed on the waiting list. In case someone still cancels it would mean you still get to come! We will contact you in due time if you are still eligible for joining. 
                    <p>
                    <b>We will not charge you with costs in case you are on the waiting list.</b>
                </div>
            <?php endif ?>
            <form method="POST">
                <input type="hidden" name="type" value="First-year">
                <h3>Personal</h3>
                <?= $form->render_field('student_number', ['placeholder' => 's1234567']) ?>
                <?= $form->render_field('first_name', ['placeholder' => 'Jan']) ?>
                <?= $form->render_field('surname', ['placeholder' => 'de Joker']) ?>
                <?= $form->render_field('birthday', ['placeholder' => '20-09-1993']) ?>
                <h3>Contact</h3>
                <?= $form->render_field('address', ['placeholder' => 'Nijenborgh 9']) ?>
                <?= $form->render_field('postal_code', ['placeholder' => '9747 AG']) ?>
                <?= $form->render_field('city', ['placeholder' => 'Groningen']) ?>
                <?= $form->render_field('email', ['placeholder' => 'introcee@svcover.nl']) ?>
                <?= $form->render_field('phone', ['placeholder' => '+316 1234 5678']) ?>
                <?= $form->render_field('emergency_phone', ['placeholder' => '+3150 363 6898']) ?>
                <h3>Financial</h3>
                <?= $form->render_field('iban', ['placeholder' => 'NL37BANK0123456789']) ?>
                <?= $form->render_field('bic', ['placeholder' => 'BANKNL2G']) ?>
                <h3>Other</h3>
                <?= $form->render_field('study') ?>
                <?= $form->render_field('remarks', ['placeholder' => 'Comments (allergies, medication, remarks)', 'rows'=>3]) ?>
                <?= $form->render_field('vegetarian') ?>
                <div class="checkbox <?= empty($form->get_field('accept_terms')->errors) ? '' : 'has-error' ?>">
                    <label>
                        <?= $form->get_field('accept_terms')->render() ?>
                        I have read and accepted the <a href='/static/docs/Terms-and-Conditions-Introduction-Camp-Cover-2018.pdf'>terms and conditions</a>
                    </label>
                </div>
                <div class="checkbox <?= empty($form->get_field('accept_costs')->errors) ? '' : 'has-error' ?>">
                    <label>
                        <?= $form->get_field('accept_costs')->render() ?>
                        I have accepted the costs of &euro; 45,-
                    </label>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
        <div role="tabpanel" class="tab-pane <?=($form->get_value('type') != 'First-year') ? 'active' : '' ?>" id="senior">
            <?php if (count( array_filter(get_model('Registration')->get(), function ($p) {
                    return $p['status'] === 'registered' && $p['type'] !== 'First-year';
                })) >= 30): ?>
                <p>
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    At this moment all the reserved spots for the introductory camp are taken. You can still sign up, and we recommend to do so, but you will be placed on the waiting list. In case someone still cancels it would mean you still get to come! We will contact you in due time if you are still eligible for joining. 
                    <p>
                    <b>We will not charge you with costs in case you are on the waiting list.</b>
                </div>
            <?php endif ?>
            <form method="POST">
                <input type="hidden" name="type" value="Senior">
                <h3>Personal</h3>
                <?= $form->render_field('first_name', ['placeholder' => 'Jan']) ?>
                <?= $form->render_field('surname', ['placeholder' => 'de Joker']) ?>
                <?= $form->render_field('birthday', ['placeholder' => '20-09-1993']) ?>
                <h3>Contact</h3>
                <?= $form->render_field('address', ['placeholder' => 'Nijenborgh 9']) ?>
                <?= $form->render_field('postal_code', ['placeholder' => '9747 AG']) ?>
                <?= $form->render_field('city', ['placeholder' => 'Groningen']) ?>
                <?= $form->render_field('email', ['placeholder' => 'introcee@svcover.nl']) ?>
                <?= $form->render_field('phone', ['placeholder' => '+3150 363 6898']) ?>
                <?= $form->render_field('emergency_phone', ['placeholder' => '+3150 363 6898']) ?>
                <h3>Financial</h3>
                <?= $form->render_field('iban', ['placeholder' => 'NL37BANK0123456789']) ?>
                <?= $form->render_field('bic', ['placeholder' => 'BANKNL2G']) ?>
                <h3>Other</h3>
                <?= $form->render_field('study') ?>
                <?= $form->render_field('study_year') ?>
                <?= $form->render_field('remarks', ['placeholder' => 'Comments (allergies, medication, remarks)', 'rows'=>3]) ?>
                <?= $form->render_field('mentor') ?>
                <?= $form->render_field('vegetarian') ?>
                <div class="checkbox <?= empty($form->get_field('accept_terms')->errors) ? '' : 'has-error' ?>">
                    <label>
                        <?= $form->get_field('accept_terms')->render() ?>
                        I have read and accepted the <a href='/static/docs/Terms-and-Conditions-Introduction-Camp-Cover-2018.pdf'>terms and conditions</a>
                    </label>
                </div>
                <div class="checkbox <?= empty($form->get_field('accept_costs')->errors) ? '' : 'has-error' ?>">
                    <label>
                        <?= $form->get_field('accept_costs')->render() ?>
                        I have accepted the costs of &euro; 55,-
                    </label>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<?php $this->end() ?>

<?php $this->begin('scripts') ?>
<script type="text/javascript">
    $('#myTabs a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    });
</script>
<?php $this->end() ?>

