<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <h1>Sign up</h1>
    <h2>Barbecue on the introduction day</h2>
    <?php if (cover_session_logged_in()): ?>
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Hi <?= get_cover_session()->voornaam ?>! We prefilled the form with some your information from the Cover website.
        </div>
    <?php else: ?>
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Hi there! Did you know, that if you log in on the Cover website (membership required) we can pretty much fill in most of this information already? You can log in <a href='//www.svcover.nl/sessions.php'>here</a>, or sign up <a href='//www.svcover.nl/lidworden.php'>here</a>.
        </div>
    <?php endif ?>
    <ul class="nav nav-pills nav-justified" role="tablist">
        <li role="presentation" <?php if ($form->get_value('type') == 'First-year'): ?>class="active"<?php endif ?>>
            <a href="#first-year" aria-controls="first-year" role="tab" data-toggle="tab">First-year students</a>
        </li>
        <li role="presentation" <?php if ($form->get_value('type') != 'First-year'): ?>class="active"<?php endif ?>>
            <a href="#senior" aria-controls="senior" role="tab" data-toggle="tab">Senior students</a>
        </li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane <?=($form->get_value('type') == 'First-year') ? 'active' : '' ?>" id="first-year">
            <form method="POST">
                <input type="hidden" name="type" value="First-year">
                <h3>Personal</h3>
                <?= $form->render_field('first_name', ['placeholder' => 'Jan']) ?>
                <?= $form->render_field('surname', ['placeholder' => 'de Joker']) ?>
                <?= $form->render_field('birthday', ['placeholder' => '20-09-1993']) ?>
                <h3>Contact</h3>
                <?= $form->render_field('address', ['placeholder' => 'Nijenborgh 9']) ?>
                <?= $form->render_field('city', ['placeholder' => 'Groningen']) ?>
                <?= $form->render_field('email', ['placeholder' => 'introcee@svcover.nl']) ?>
                <h3>Financial</h3>
                <?= $form->render_field('iban', ['placeholder' => 'NL37BANK0123456789']) ?>
                <?= $form->render_field('bic', ['placeholder' => 'BANKNL2G']) ?>
                <h3>Other</h3>
                <?= $form->render_field('study') ?>
                <?= $form->render_field('remarks', ['placeholder' => 'Comments (allergies, remarks)', 'rows'=>3]) ?>
                <?= $form->render_field('vegetarian') ?>
                <div class="checkbox <?= empty($form->get_field('accept_costs')->errors) ? '' : 'has-error' ?>">
                    <label>
                        <?= $form->get_field('accept_costs')->render() ?>
                        I have accepted the costs for whatever I drink at the introduction day barbecue
                    </label>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
        <div role="tabpanel" class="tab-pane <?=($form->get_value('type') != 'First-year') ? 'active' : '' ?>" id="senior">
            <form method="POST">
                <input type="hidden" name="type" value="First-year">
                <h3>Personal</h3>
                <?= $form->render_field('first_name', ['placeholder' => 'Jan']) ?>
                <?= $form->render_field('surname', ['placeholder' => 'de Joker']) ?>
                <?= $form->render_field('birthday', ['placeholder' => '20-09-1993']) ?>
                <h3>Contact</h3>
                <?= $form->render_field('address', ['placeholder' => 'Nijenborgh 9']) ?>
                <?= $form->render_field('city', ['placeholder' => 'Groningen']) ?>
                <?= $form->render_field('email', ['placeholder' => 'introcee@svcover.nl']) ?>
                <h3>Financial</h3>
                <?= $form->render_field('iban', ['placeholder' => 'NL37BANK0123456789']) ?>
                <?= $form->render_field('bic', ['placeholder' => 'BANKNL2G']) ?>
                <h3>Other</h3>
                <?= $form->render_field('study') ?>
                <?= $form->render_field('remarks', ['placeholder' => 'Comments (allergies or remarks)', 'rows'=>3]) ?>
                <?= $form->render_field('vegetarian') ?>
                <div class="checkbox <?= empty($form->get_field('accept_costs')->errors) ? '' : 'has-error' ?>">
                    <label>
                        <?= $form->get_field('accept_costs')->render() ?>
                        I have accepted the costs for whatever I drink at the introduction day barbecue + &euro; 5,-
                    </label>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
<?php $this->end() ?>

<?php $this->begin('scripts') ?>
<script type="text/javascript">
    $('#myTabs a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    });
</script>
<?php $this->end() ?>

